import { useState, useEffect } from 'react';
import { api } from '../api';
import Dropdown from '../components/Dropdown';
import PBadChart from '../components/PBadChart';
import ForecastCard from '../components/ForecastCard';
import { RiskBadge } from '../components/RiskBadge';
import { SkeletonChart, SkeletonForecastGrid } from '../components/Skeleton';
import MarkdownResponse from '../components/MarkdownResponse';
import { RefreshIcon, AlertIcon } from '../components/icons';

const METRIC_DEFS = [
  { key: 'precip_24h_mm',   label: 'Precip · 24h', unit: 'mm' },
  { key: 'precip_recent_3h', label: 'Precip · last 3h', unit: 'mm' },
  { key: 'wind_max_kmh',    label: 'Wind max', unit: 'km/h' },
  { key: 'wave_max_m',      label: 'Wave max', unit: 'm' },
  { key: 'sea_temp_c',      label: 'Sea temp', unit: '°C' },
  { key: 'tide_range_m',    label: 'Tide range', unit: 'm' },
];

const fmt = (v, unit) =>
  v == null ? '—' : `${Number(v).toFixed(unit === 'm' || unit === '°C' ? 1 : 0)}${unit ? ' ' + unit : ''}`;

export default function Forecast() {
  const [sites, setSites] = useState([]);
  const [siteOptions, setSiteOptions] = useState([]);
  const [selectedSite, setSelectedSite] = useState('dauin_muck');
  const [briefing, setBriefing] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    api.getSites()
      .then((s) => {
        setSites(s || []);
        setSiteOptions((s || []).map((site) => ({
          value: site.key,
          label: site.name,
          description: site.type,
        })));
      })
      .catch(console.error);
  }, []);

  useEffect(() => {
    let cancel = false;
    setLoading(true);
    setError(null);
    api.getBriefing(selectedSite)
      .then((b) => !cancel && setBriefing(b))
      .catch((err) => !cancel && setError(err.message))
      .finally(() => !cancel && setLoading(false));
    return () => { cancel = true; };
  }, [selectedSite]);

  const refresh = () => {
    setLoading(true);
    api.getBriefing(selectedSite).then(setBriefing).finally(() => setLoading(false));
  };

  return (
    <div>
      <header className="page-header">
        <div>
          <h1 className="page-title">Forecast</h1>
          <p className="page-subtitle">AI briefing and feature snapshot for the next 48 hours</p>
        </div>
        <div className="flex gap-3" style={{ minWidth: 360 }}>
          {siteOptions.length > 0 && (
            <div style={{ flex: 1 }}>
              <Dropdown
                id="forecast-site"
                ariaLabel="Select dive site"
                value={selectedSite}
                onChange={setSelectedSite}
                options={siteOptions}
                placeholder="Select site"
              />
            </div>
          )}
          <button className="btn btn--secondary" onClick={refresh} disabled={loading}>
            {loading ? <span className="spinner" /> : <RefreshIcon size={14} />}
            <span>Refresh</span>
          </button>
        </div>
      </header>

      {error && (
        <div className="banner banner--danger">
          <span className="banner__icon"><AlertIcon size={16} /></span>
          <div>
            <div className="banner__title">Briefing unavailable</div>
            <div className="banner__body">{error}</div>
          </div>
        </div>
      )}

      {loading && !briefing ? (
        <div style={{ display: 'grid', gap: 'var(--space-5)' }}>
          <SkeletonChart />
          <SkeletonForecastGrid />
        </div>
      ) : (
        <div className="grid-12" style={{ marginTop: 'var(--space-5)' }}>
          <section className="span-7 section">
            <div className="section__head">
              <div>
                <h2 className="section__title">Briefing</h2>
                <p className="section__sub">Generated by the SeaSID agent with live weather, tide, and model output</p>
              </div>
            </div>
            <div className="section__body">
              {briefing ? (
                <MarkdownResponse>{briefing.response || ''}</MarkdownResponse>
              ) : (
                <div className="empty">No briefing returned.</div>
              )}
            </div>
          </section>

          <aside className="span-5 section">
            <div className="section__head">
              <div>
                <h2 className="section__title">Live features</h2>
                <p className="section__sub">11-feature snapshot for the current hour</p>
              </div>
            </div>
            <div className="section__body">
              {briefing && briefing.tool_calls ? (
                <FeatureSnapshot toolCalls={briefing.tool_calls} />
              ) : (
                <div className="empty">No feature snapshot yet.</div>
              )}
            </div>
          </aside>
        </div>
      )}
    </div>
  );
}

function FeatureSnapshot({ toolCalls }) {
  const fc = toolCalls.find((t) => t.name === 'get_forecast');
  const wt = toolCalls.find((t) => t.name === 'get_weather');

  if (!fc) return <div className="empty">No data</div>;

  let parsed = {};
  try { parsed = JSON.parse(fc.result || '{}'); } catch {}

  return (
    <dl className="deflist">
      {METRIC_DEFS.map((m) => {
        const v = parsed.features?.[m.key] ?? wt ? extract(wt, m.key) : null;
        return (
          <div key={m.key} style={{ display: 'contents' }}>
            <dt>{m.label}</dt>
            <dd>{fmt(v, m.unit)}</dd>
          </div>
        );
      })}
      <div style={{ display: 'contents' }}>
        <dt>Overall risk</dt>
        <dd><RiskBadge risk={parsed.overall_risk || '—'} /></dd>
      </div>
    </dl>
  );
}

function extract(toolCall, key) {
  try { return JSON.parse(toolCall.result || '{}')?.weather?.[key]; } catch { return null; }
}
