"""Authentication and authorization helpers for SeaSID's API."""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import os
import secrets
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import Any

import jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from app.lib.sites import site_keys


AUTH_ISSUER = "seasid"
DEFAULT_TOKEN_MINUTES = 60
VALID_ROLES = {"viewer", "operator", "data_steward", "admin"}
bearer_scheme = HTTPBearer(auto_error=False)

# Bootstrap credentials used when neither SEASID_AUTH_USERS_JSON nor the
# single-admin variables are set. These are intentionally weak and clearly
# labelled so they stand out in any non-dev environment. Set
# SEASID_AUTH_REQUIRE_EXPLICIT_USERS=true (or configure real users) in
# production to disable them.
DEV_DEFAULT_SECRET = "seasid-dev-default-secret-do-not-use-in-production-x"

DEV_DEFAULT_USERS: tuple[dict[str, Any], ...] = (
    {
        "username": "admin",
        "password": "admin-dev",
        "role": "admin",
        "site_keys": ["*"],
    },
    {
        "username": "steward",
        "password": "steward-dev",
        "role": "data_steward",
        "site_keys": ["*"],
    },
    {
        "username": "dauin-operator",
        "password": "operator-dev",
        "role": "operator",
        "site_keys": ["dauin_muck"],
    },
    {
        "username": "reef-operator",
        "password": "operator-dev",
        "role": "operator",
        "site_keys": ["apo_reef"],
    },
    {
        "username": "viewer",
        "password": "viewer-dev",
        "role": "viewer",
        "site_keys": ["*"],
    },
)

_dev_defaults_warned = False
logger = logging.getLogger("seasid.auth")


@dataclass(frozen=True)
class Principal:
    subject: str
    username: str
    role: str
    site_keys: tuple[str, ...]
    authenticated: bool = True

    def as_user_info(self) -> dict[str, Any]:
        return {
            "subject": self.subject,
            "username": self.username,
            "role": self.role,
            "site_keys": list(self.site_keys),
        }


@dataclass(frozen=True)
class ConfiguredUser:
    subject: str
    username: str
    role: str
    site_keys: tuple[str, ...]
    password: str | None = None
    password_hash: str | None = None


def auth_enabled() -> bool:
    """Return whether protected routes require bearer authentication."""
    return (os.getenv("SEASID_AUTH_ENABLED", "true").strip().lower()
            not in {"0", "false", "no", "off"})


def token_expiry_minutes() -> int:
    try:
        return max(5, int(os.getenv("SEASID_ACCESS_TOKEN_MINUTES", DEFAULT_TOKEN_MINUTES)))
    except ValueError:
        return DEFAULT_TOKEN_MINUTES


def auth_secret() -> str:
    explicit = os.getenv("SEASID_AUTH_SECRET", "").strip()
    if explicit:
        return explicit
    if auth_enabled() and not _require_explicit_users():
        _warn_dev_defaults_once()
        return DEV_DEFAULT_SECRET
    return ""


def _parse_site_keys(value: Any) -> tuple[str, ...]:
    if value is None:
        return ("*",)
    if isinstance(value, str):
        values = [item.strip() for item in value.split(",") if item.strip()]
    elif isinstance(value, list):
        values = [str(item).strip() for item in value if str(item).strip()]
    else:
        values = []
    return tuple(values or ["*"])


def _require_explicit_users() -> bool:
    """Return True if dev defaults must NOT be used as a fallback."""
    flag = os.getenv("SEASID_AUTH_REQUIRE_EXPLICIT_USERS", "").strip().lower()
    return flag in {"1", "true", "yes", "on"}


def _warn_dev_defaults_once() -> None:
    global _dev_defaults_warned
    if _dev_defaults_warned:
        return
    _dev_defaults_warned = True
    logger.warning(
        "SeaSID is using built-in DEV DEFAULT credentials (admin/admin-dev, "
        "steward/steward-dev, dauin-operator/operator-dev, "
        "reef-operator/operator-dev, viewer/viewer-dev) and a placeholder "
        "JWT secret. Set SEASID_AUTH_USERS_JSON (or SEASID_ADMIN_USERNAME + "
        "SEASID_ADMIN_PASSWORD) and SEASID_AUTH_SECRET (>=32 chars) before "
        "any non-dev deployment, or set SEASID_AUTH_REQUIRE_EXPLICIT_USERS=true "
        "to disable this fallback."
    )


def configured_users() -> tuple[ConfiguredUser, ...]:
    """Load users from JSON or the single-admin bootstrap variables.

    JSON records may contain either ``password_hash`` or ``password``. The
    latter is convenient for local development; production deployments should
    use a PBKDF2 hash generated by ``scripts.hash_password``.

    If neither source yields any users and authentication is enabled, this
    function falls back to :data:`DEV_DEFAULT_USERS` so a fresh checkout can
    log in immediately. Production deployments can disable that fallback by
    setting ``SEASID_AUTH_REQUIRE_EXPLICIT_USERS=true``.
    """
    raw_users = os.getenv("SEASID_AUTH_USERS_JSON", "").strip()
    if raw_users:
        try:
            records = json.loads(raw_users)
        except json.JSONDecodeError as exc:
            raise RuntimeError("SEASID_AUTH_USERS_JSON is not valid JSON") from exc
        if not isinstance(records, list):
            raise RuntimeError("SEASID_AUTH_USERS_JSON must be a JSON list")
    else:
        username = os.getenv("SEASID_ADMIN_USERNAME", "").strip()
        password = os.getenv("SEASID_ADMIN_PASSWORD", "")
        records = ([{
            "username": username,
            "password": password,
            "role": "admin",
            "site_keys": ["*"],
        }] if username and password else [])

    users: list[ConfiguredUser] = []
    for record in records:
        if not isinstance(record, dict):
            continue
        username = str(record.get("username", "")).strip()
        role = str(record.get("role", "viewer")).strip().lower()
        if not username or role not in VALID_ROLES:
            continue
        users.append(ConfiguredUser(
            subject=str(record.get("subject") or username),
            username=username,
            role=role,
            site_keys=_parse_site_keys(record.get("site_keys")),
            password=record.get("password"),
            password_hash=record.get("password_hash"),
        ))

    if not users and auth_enabled() and not _require_explicit_users():
        _warn_dev_defaults_once()
        for record in DEV_DEFAULT_USERS:
            users.append(ConfiguredUser(
                subject=record["username"],
                username=record["username"],
                role=record["role"],
                site_keys=_parse_site_keys(record["site_keys"]),
                password=record["password"],
                password_hash=None,
            ))
    return tuple(users)



def get_active_users():
    """Return ConfiguredUser records preferring the DB, with env/dev fallback.

    On first boot, copies env-loaded users into the DB so admins can manage
    them via the API without losing the existing setup.
    """
    try:
        from app.lib import user_store, db as _db
    except Exception:
        return configured_users()
    try:
        # Lazy table creation so this also runs before the app starts FastAPI.
        _db.Base.metadata.create_all(bind=_db.engine)
        rows = _db.SessionLocal().query(_db.User).all()
    except Exception:
        return configured_users()
    if rows:
        result = []
        for row in rows:
            # user_store keeps password_hash only; the auth path verifies via hash.
            from app.lib.user_store import _parse_site_keys
            result.append(ConfiguredUser(
                subject=row.subject,
                username=row.username,
                role=row.role,
                site_keys=_parse_site_keys(row.site_keys_json),
                password=None,
                password_hash=row.password_hash,
            ))
        return tuple(result)
    # First-boot population: copy from configured_users() into the DB.
    try:
        seed = configured_users()
        if seed:
            user_store.seed_from_auth_loader(seed)
    except Exception:
        pass
    return configured_users()


def _derive_password_hash(password: str, salt: bytes, iterations: int) -> bytes:
    return hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt,
        iterations,
        dklen=32,
    )


def hash_password(password: str, iterations: int = 310_000) -> str:
    """Create a portable PBKDF2-SHA256 password hash string."""
    salt = secrets.token_bytes(16)
    digest = _derive_password_hash(password, salt, iterations)

    def encode(value: bytes) -> str:
        return base64.urlsafe_b64encode(value).decode("ascii").rstrip("=")

    return f"pbkdf2_sha256${iterations}${encode(salt)}${encode(digest)}"


def verify_password(password: str, expected: str | None, expected_hash: str | None) -> bool:
    if expected_hash:
        try:
            scheme, iterations_text, salt_text, digest_text = expected_hash.split("$", 3)
            if scheme != "pbkdf2_sha256":
                return False
            iterations = int(iterations_text)
            padding = "=" * (-len(salt_text) % 4)
            salt = base64.urlsafe_b64decode(salt_text + padding)
            padding = "=" * (-len(digest_text) % 4)
            expected_digest = base64.urlsafe_b64decode(digest_text + padding)
            actual_digest = _derive_password_hash(password, salt, iterations)
            return hmac.compare_digest(actual_digest, expected_digest)
        except (TypeError, ValueError):
            return False
    if expected is None:
        return False
    return hmac.compare_digest(password, str(expected))


def authenticate_user(username: str, password: str) -> Principal | None:
    if not auth_enabled():
        return Principal("dev", "dev", "admin", ("*",), authenticated=False)
    try:
        users = get_active_users()
    except RuntimeError:
        return None
    for user in users:
        if hmac.compare_digest(username, user.username) and verify_password(
            password, user.password, user.password_hash,
        ):
            try:
                from app.lib.user_store import record_login
                record_login(user.subject)
            except Exception:
                pass
            return Principal(
                user.subject,
                user.username,
                user.role,
                user.site_keys,
            )
    return None


def create_access_token(principal: Principal) -> tuple[str, int]:
    secret = auth_secret()
    if auth_enabled() and len(secret) < 32:
        raise RuntimeError("SEASID_AUTH_SECRET must contain at least 32 characters")
    expiry_minutes = token_expiry_minutes()
    now = datetime.now(timezone.utc)
    payload = {
        "iss": AUTH_ISSUER,
        "sub": principal.subject,
        "username": principal.username,
        "role": principal.role,
        "site_keys": list(principal.site_keys),
        "iat": now,
        "exp": now + timedelta(minutes=expiry_minutes),
    }
    return jwt.encode(payload, secret, algorithm="HS256"), expiry_minutes * 60


def get_current_principal(
    credentials: HTTPAuthorizationCredentials | None = Depends(bearer_scheme),
) -> Principal:
    if not auth_enabled():
        return Principal("dev", "dev", "admin", ("*",), authenticated=False)
    if credentials is None or credentials.scheme.lower() != "bearer":
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required",
            headers={"WWW-Authenticate": "Bearer"},
        )
    secret = auth_secret()
    if len(secret) < 32:
        raise HTTPException(status_code=503, detail="Authentication is not configured")
    try:
        payload = jwt.decode(
            credentials.credentials,
            secret,
            algorithms=["HS256"],
            issuer=AUTH_ISSUER,
        )
        subject = str(payload["sub"])
        username = str(payload["username"])
        role = str(payload["role"])
        site_scope = _parse_site_keys(payload.get("site_keys"))
    except (jwt.PyJWTError, KeyError, TypeError, ValueError):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired authentication token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    if not subject or not username or role not in VALID_ROLES:
        raise HTTPException(status_code=401, detail="Invalid authentication token")
    return Principal(subject, username, role, site_scope)


def ensure_role(principal: Principal, *roles: str) -> None:
    if auth_enabled() and principal.role not in set(roles):
        raise HTTPException(status_code=403, detail="Insufficient permissions")


def ensure_site_access(principal: Principal, requested_site: str | None) -> None:
    if not auth_enabled():
        return
    if requested_site in (None, "all"):
        if "*" not in principal.site_keys:
            raise HTTPException(status_code=403, detail="Site-wide access is not allowed")
        return
    if requested_site not in site_keys():
        return
    if "*" not in principal.site_keys and requested_site not in principal.site_keys:
        raise HTTPException(status_code=403, detail="You are not assigned to this site")
